name: untitled
description: "aibird"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^8.1.2
  google_fonts: ^6.2.1
  lottie: ^3.1.2
  tflite_web: ^0.2.2
  cupertino_icons: ^1.0.2
  image: ^3.0.1
  js: ^0.7.1
  http: ^1.2.2
  image_picker: ^0.8.5+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_web_compilers: ^4.0.11

flutter:
  uses-material-design: true
  assets:
    - assets/
